import React from 'react';
import styled, { keyframes } from 'styled-components';

export default function WhatWeDo() {
  return (
    <Container> <H1>What Parametriks does {"{"}and why it’s better{"}"}</H1>
      <Box>
        <BoxLeft>
          <Container>
            <img src="./IoT icon.png" width={300} height={180} style={{ marginTop: '7rem' }} />
            <H3>Real-time IoT dataflows</H3>
            <TextBodyLeft>The Parametriks solution begins with obtaining historical and real-time (IoT) data from insured parties. Using the data, we build algorithms that predict where and when issues in the asset might arise ahead of time, enabling pre-emptive action. A user-friendly dashboard is also built for each stakeholder.</TextBodyLeft>
          </Container>
        </BoxLeft>
        <BoxCenter>
          <Container><img src="./generativeai_icon.jpeg" width={300} height={180} style={{ marginTop: '7rem', marginLeft: '25%' }} />
            <H3>Embedded GenAI</H3>
            <TextBody>Generative AI provides a whole new way for users to interact with data. Our GenAI chatbot will be digests the data generated by our assets and algorithms giving you actionable insights which you can immediately use. </TextBody>
          </Container></BoxCenter>
        <BoxRight><Container><img src='./910730.png' width={300} height={180} style={{ marginTop: '6rem', marginLeft: '10%' }} />
          <H3 style={{ marginLeft: '3rem', marginTop: '1rem' }}>Applied to Insurance</H3>
          <TextBodyRight>Better facilities management = healthier risk profile. This makes asset owners more attractive to insurers, and simultaneously allows insureds to pay lower insurance premiums. Win-win. </TextBodyRight>
        </Container></BoxRight>
      </Box>
    </Container>
  );
}

const Box = styled.div`
width: 100%;
  display: flex;
`;

const BoxLeft = styled.div`
width: 25%;
  display: flex;
`;

const BoxCenter = styled.div`
width: 50%;
  display: flex;
`;

const BoxRight = styled.div`
width: 25%;
  display: flex;
`;

const Container = styled.div`
  position: relative;
  max-width: 130em;
  width: 100%;
  margin: 0 auto;
  padding: 0 2rem;
  color: black;
  height: 70vh;
`;

const H1 = styled.div`
color: #320CFA;
font-family: tahoma;
font-size: 3rem;
font-weight: 100;
line-height: 1.5;
text-transform: uppercase;
white-space: nowrap;
overflow: hidden;
position: relative;
width: 100h;

text-align: center; /* Center the text horizontally */
`;

const H2 = styled.div`
color: black;
// font-family: tahoma;
font-size: 2rem;
font-weight: 100;
line-height: 1.5;
text-transform: uppercase;
white-space: nowrap;
overflow: hidden;
position: relative;
width: 100h;
margin-top: 5rem;
text-align: center; /* Center the text horizontally */
`;
const H3 = styled.div`
color: #DD3166;
// font-family: tahoma;
font-size: 2rem;
font-weight: 100;
line-height: 1.5;
text-transform: uppercase;
white-space: nowrap;
overflow: hidden;
position: relative;
width: 100h;
// margin-top: 5rem;
text-align: center; /* Center the text horizontally */
font-weight: bold
`;

const TextBody = styled.div`
color: black;
font-family: tahoma;
font-size: 1.8rem;
font-weight: 100;
line-height: 1.5;
// white-space: nowrap;
// overflow: hidden;
position: relative;
width: 50%;
margin-top: 3rem;
text-align: center; /* Center the text horizontally */
// font-weight: bold
margin-left: 25%
`;

const TextBodyLeft = styled.div`
color: black;
font-family: tahoma;
font-size: 1.8rem;
font-weight: 100;
line-height: 1.5;
// white-space: nowrap;
// overflow: hidden;
position: relative;
width: 100%;
margin-top: 3rem;
text-align: center; /* Center the text horizontally */
// font-weight: bold
// margin-left: 25%
`;

const TextBodyRight = styled.div`
color: black;
font-family: tahoma;
font-size: 1.8rem;
font-weight: 100;
line-height: 1.5;
// white-space: nowrap;
// overflow: hidden;
position: relative;
width: 100%;
margin-top: 3rem;
text-align: center; /* Center the text horizontally */
// font-weight: bold
margin-left: 15%
`;

const Message = styled.div`
  background-color: yellow;
  color: #333;
  display: block;
  font-weight: 900;
  overflow: hidden;
  position: absolute;
  padding-left: 0.5rem;
  top: 0.2rem;
  left: 270px;
  animation: openclose 5s ease-in-out infinite;
`;